// console.log(undefined == 0);
// console.log(undefined >= 0);
// console.log(undefined < 0);
// console.log(undefined > null);
// console.log(undefined == null);
// console.log(undefined == NaN);
// console.log(undefined <= NaN);
// console.log(undefined === undefined)
// console.log(undefined === null);
// console.log(undefined >= NaN);